// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protoUtil/Sample.proto

package protoUtil

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Sample struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Label                string   `protobuf:"bytes,2,opt,name=Label,proto3" json:"Label,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=Description,proto3" json:"Description,omitempty"`
	Version              int32    `protobuf:"varint,4,opt,name=Version,proto3" json:"Version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Sample) Reset()         { *m = Sample{} }
func (m *Sample) String() string { return proto.CompactTextString(m) }
func (*Sample) ProtoMessage()    {}
func (*Sample) Descriptor() ([]byte, []int) {
	return fileDescriptor_9bc8b17beed86b9c, []int{0}
}

func (m *Sample) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Sample.Unmarshal(m, b)
}
func (m *Sample) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Sample.Marshal(b, m, deterministic)
}
func (m *Sample) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Sample.Merge(m, src)
}
func (m *Sample) XXX_Size() int {
	return xxx_messageInfo_Sample.Size(m)
}
func (m *Sample) XXX_DiscardUnknown() {
	xxx_messageInfo_Sample.DiscardUnknown(m)
}

var xxx_messageInfo_Sample proto.InternalMessageInfo

func (m *Sample) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Sample) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *Sample) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Sample) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func init() {
	proto.RegisterType((*Sample)(nil), "protoUtil.Sample")
}

func init() { proto.RegisterFile("protoUtil/Sample.proto", fileDescriptor_9bc8b17beed86b9c) }

var fileDescriptor_9bc8b17beed86b9c = []byte{
	// 129 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2b, 0x28, 0xca, 0x2f,
	0xc9, 0x0f, 0x2d, 0xc9, 0xcc, 0xd1, 0x0f, 0x4e, 0xcc, 0x2d, 0xc8, 0x49, 0xd5, 0x03, 0x0b, 0x08,
	0x71, 0xc2, 0xc5, 0x95, 0xb2, 0xb8, 0xd8, 0x20, 0x52, 0x42, 0x7c, 0x5c, 0x4c, 0x9e, 0x29, 0x12,
	0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x4c, 0x9e, 0x29, 0x42, 0x22, 0x5c, 0xac, 0x3e, 0x89, 0x49,
	0xa9, 0x39, 0x12, 0x4c, 0x60, 0x21, 0x08, 0x47, 0x48, 0x81, 0x8b, 0xdb, 0x25, 0xb5, 0x38, 0xb9,
	0x28, 0xb3, 0xa0, 0x24, 0x33, 0x3f, 0x4f, 0x82, 0x19, 0x2c, 0x87, 0x2c, 0x24, 0x24, 0xc1, 0xc5,
	0x1e, 0x96, 0x5a, 0x54, 0x0c, 0x92, 0x65, 0x51, 0x60, 0xd4, 0x60, 0x0d, 0x82, 0x71, 0x93, 0xd8,
	0xc0, 0xd6, 0x1a, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x2d, 0xa2, 0xb8, 0x9d, 0x97, 0x00, 0x00,
	0x00,
}
